### ISSUE TITLE
Focus more on intro

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-documentation#10]
Right now, the installation guide is the first thing you see when you access the documentation. This should not be the case, because most visitors are users, not administrators.

I think we should make https://www.opendevstack.org/ods-documentation/common/latest/getting-started/introduction.html the first page.

**Comment by rattermeyer** [comment]
Agreed, but if you access documentation from the landing page via the documentation link, you are already there, but I will change the default.
