### ISSUE TITLE
store local build result in separate directroy

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-documentation#13]
Modify playbooks site-workspace.yml and site-workspace-full.yml, so that documentation is not written to directory _docs_, use _local_build_instead. Add directory _local_build_ to git ignore.

Only travis-ci build writes to _docs_ directory by using playbook site.yml

**Comment by rattermeyer** [comment]
I think this is a good idea, as it prevents doc changes commited from local environment.
If someone forgets to revert changes to the '/docs' directory, it will clutter the PR.
So thumbs up for this enhancement
