### ISSUE TITLE
Collect user upgrade guide information for ODS 2.0

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-documentation#23]
The purpose of this issue is to collect all information that users need to know (or which would help them understand what is new) when they upgrade their projects from ODS 1.2.0 to 2.0.

**Comment by michaelsauter** [comment]
In the shared lib, one can now require a passing quality gate for SonarQube.

**Comment by michaelsauter** [comment]
In the shared lib, rollouts will be triggered manually when no config/image trigger exists on the DC.

**Comment by michaelsauter** [comment]
nodejs8 slave is discontinued. Users either need to stay on the image they currently use or migrate to nodejs10.

**Comment by gerardcl** [comment]
they need to udpate the memership configs in their projects (see current create-projects.sh)

**Comment by michaelsauter** [comment]
@gerardcl please be more specific :) are you referring to your PR today?

**Comment by michaelsauter** [comment]
No more nodejs8 slave (https://github.com/opendevstack/ods-quickstarters/pull/71), users should update to nodejs10.

**Comment by michaelsauter** [comment]
Tailor has been updated to 0.11.0 in the Jenkins slaves, see https://github.com/opendevstack/ods-core/pull/290.

**Comment by michaelsauter** [comment]
When working with images, Skopeo is now part of the Jenkins slaves, see https://github.com/opendevstack/ods-core/issues/253.

**Comment by michaelsauter** [comment]
There are now memory quotas (#12) and CPU quotas (#74), users of existing components should configure those as well.

**Comment by michaelsauter** [comment]
Enable WSGI for ds-ml-service quickstarter (#37)

**Comment by michaelsauter** [comment]
Switch to OAuth proxy in jupyter-notebook and r-shiny quickstarters (#46)

**Comment by michaelsauter** [comment]
Airflow Quickstarter fully provisioned in user's ODS project (#60)

**Comment by gerardcl** [comment]
shared-services, shared-images have been deprecated in ODS2
- (opendevstack/ods-quickstarters/issues/60)
- (opendevstack/ods-core/issues/215)

**Comment by gerardcl** [comment]
howto: switch to project specific cd_user in an existing ODS project

**Comment by gerardcl** [comment]
howto: provision components from other (private/testing) repos

**Comment by michaelsauter** [comment]
For

> howto: provision components from other (private/testing) repos

I do not see a need in the "update guide", but I agree it should be added as a general section in the "user documentation" ...
