### ISSUE TITLE
Discussion: Integration of Search into documentation

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-documentation#3]
We should include some search functionality.

Ideas:

* based on https://github.com/Mogztter/antora-lunr
or
* based on https://community.algolia.com/docsearch/ (https://community.algolia.com/docsearch/who-can-apply.html) 

What would you choose, if any?

**Comment by tbugfinder** [comment]
I've evaluated both options.

**Antora-lunr** doesn't have external dependencies.

<img width="899" alt="Bildschirmfoto 2019-12-27 um 21 34 12" src="https://user-images.githubusercontent.com/15378237/71531903-1010fe80-28f1-11ea-842a-ff808f572a73.png">


**Algolia** requires an account but is free for open source projects.
Building the search index could be done within travis or within Algolia itself.
<img width="732" alt="Bildschirmfoto 2019-12-27 um 20 55 06" src="https://user-images.githubusercontent.com/15378237/71531902-0d160e00-28f1-11ea-8a1b-fea66457a1cf.png">


My personal preference is Algolia.

**Comment by rattermeyer** [comment]
I am wondering that your preference is Algolia, but that you have submitted a PR for antora-lunr.
Was this by mistake in the comment above?

**Comment by tbugfinder** [comment]
Well, antora-lunr doesn't have any external dependencies, so it's easier to implement and start off with.
