### ISSUE TITLE
Running `antora generate site-workspace.yml` fails

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-documentation#30]
I get:
```
error: Cannot find module 'asciidoctor-plantuml'
Add the --stacktrace option to see the cause.
```

According to the docs, I started a PlantUML server as a docker container, which is running:
```
→ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED              STATUS              PORTS                    NAMES
892defe58534        plantuml/plantuml-server:jetty   "/docker-entrypoint.…"   About a minute ago   Up About a minute   0.0.0.0:9080->8080/tcp   cool_raman
```

What am I missing?

**Comment by stefanlack** [comment]
Module plantuml is missing. I ran into this issue some day ago and fixed locally today.
Run `npm install asciidoctor-plantuml` to install missing module
This writes file _package-lock.json_
Soon I will create a PR for this
