### ISSUE TITLE
Create Issue Templates

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-documentation#4]
Creating issue templates for your repositories / organization to make the life easier for contributors.
Reference: https://help.github.com/en/articles/creating-issue-templates-for-your-repository
Inspiration: https://github.com/devspace/awesome-github-templates

**Comment by michaelsauter** [comment]
@SimonGolms Would you be able to contribute this? That would be awesome!

**Comment by SimonGolms** [comment]
@michaelsauter I am sorry, but currently I don't have the time and resources to work out and contribute to this topic, yet and in the next months.

**Comment by michaelsauter** [comment]
@FelixWoRe Can you look into this?

**Comment by FelixWoRe** [comment]
That's the way i did it.
https://github.com/opendevstack/ods-jenkins-shared-library/pull/131
