### ISSUE TITLE
Revamp documentation

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-documentation#42]
Our documentation is not in a good shape. A lot of stuff is outdated, and the structure is also quite confusing. Let's fix this!

I am going to open PR's all over our repos which implement the following changes:

* Use one (distributed) Antora component, spread over multiple repos, instead of several components. There is no need for separate components. After a review of Antoras documentation, I believe this is better represented as multiple modules.
* Extract all documentation out of `opendevstack.github.io` - it is better to have that content closer to the code, so I will move into `ods-core`
* Present documentation for users in mind. There will only be two subsections for other target groups: one for administration, one for contribution.
* Update lots of outdated documentation (installation, Jenkins Shared library, ...)

I have some follow-up in mind, but this is already huge so I'll leave it at that.

**Comment by michaelsauter** [comment]
Here's a screenshot of a local version of this - with every navigation expanded except the quickstarters:
![Screenshot 2020-04-17 at 16 00 55](https://user-images.githubusercontent.com/215455/79577251-b2cdd280-80c4-11ea-9f5d-ee3708d56c16.png)

**Comment by michaelsauter** [comment]
There's still a lot of room for improvement, but I believe this to be a huge step.

@rattermeyer @oalyman Not sure if this is reviewable really. Have a look, but I'd propose to merge this pretty much as-is, and then it is easier to make changes from there. The only potential blocker I see is if you totally disagree with this "distributed component" change.

**Comment by sino92** [comment]
Linking a related PR https://github.com/opendevstack/opendevstack.github.io/pull/138 a small improvement that could be part of a bigger change
