### ISSUE TITLE
Remove plantuml dependency

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-documentation#46]
Right now the docs need plantuml.

However, it is only used on one page (contributing / development). I think this does not warrant the extra complexity in configuring and setting it up. The docs are already difficult to contribute to because one needs to know a little about Asciidoctor and Antora, so we should strive to make getting started as simple as possible.

**Comment by michaelsauter** [comment]
@gerardcl Since you built the diagram - would you be ok with this change?

**Comment by gerardcl** [comment]
if we can still draw diagrams yes! if not then I guess we will build diagrams aside and then load images?
no prob!

**Comment by michaelsauter** [comment]
@gerardcl yea can't draw diagrams afterwards anymore. would be annoying, but would make it easier to start documentation locally ...
