### ISSUE TITLE
[bug] faulty content structure

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-documentation#53]
1. Go to: https://www.opendevstack.org/ods-documentation
2. Looking for `Update Guide to version 2.x for OpenDevStack users`
3. Found in the `ods@3.x Preview` documentation: https://www.opendevstack.org/ods-documentation/opendevstack/3.x/update-guides/2x.html

**Comment by michaelsauter** [comment]
This is not a bug.

Any higher version also contains all the upgrade instructions for lower versions.

There will be a "Migrate to 3.x" guide as well.
