### ISSUE TITLE
Search searches in all versions

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-documentation#58]
The search turns up every hit across versions, so the "same" page can show up multiple times, which is very confusing. Ideally it would only search in the currently selected version ... or at least show which version each hit relates to.

**Comment by tbugfinder** [comment]
Duplicate of https://github.com/opendevstack/ods-documentation/issues/41 ?

**Comment by tbugfinder** [comment]
I guess results should be grouped as done, e.g. @couchbase docs. They are using Algolia as a search provider.
Tweaks within antora-lunr js might be required to get a comparable view.

https://docs.couchbase.com/home/index.html
![image](https://user-images.githubusercontent.com/15378237/96688566-9b2c1b00-1381-11eb-9528-28a4c490d138.png)

**Comment by michaelsauter** [comment]
Sorry yes duplicate of #41. 

I like the grouping approach.
