### ISSUE TITLE
travis-ci.org -> travis-ci.com migration

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-documentation#60]
Would anybody kindly check which travis-ci domain is configured? There are some discussions ongoing as a migration to travis-ci.com should be finished by end of 2020. According to the git configuration I suspect that travis-ci.org is being setup.

https://github.com/opendevstack/ods-documentation/blob/4b7f4bcd76ffca91b899bdb2247418b5f58320b5/.travis/push.sh#L5

https://travis-ci.community/t/org-to-com-migration-deadline/10260

**Comment by michaelsauter** [comment]
Thanks for bringing this up, wasn't aware of it. Maybe we could also use this as an opportunity to move to GitHub Actions. All other CI work except for the documentation is done with GitHub Actions, so it would be good to align this.

**Comment by tbugfinder** [comment]
https://github.com/opendevstack/ods-documentation/pull/62

**Comment by tbugfinder** [comment]
moved to github actions
