### ISSUE TITLE
Page Not Found for ODS 4.x

### ISSUE THREAD

**Issue by albertpuente** [opendevstack/ods-documentation#67]
[opendevstack/4.x/index.html](https://www.opendevstack.org/ods-documentation/opendevstack/4.x/index.html) does not exist anymore breaking many links.
It looks like this is related with the new 5.x Preview version in the documentation.

**Comment by metmajer** [comment]
@tbugfinder

**Comment by tbugfinder** [comment]
Created PR to add the 4.x branches.

**Comment by tbugfinder** [comment]
"5.x preview" and 4.x are now in place.
